#!/bin/bash

ASTERISK_VERSION=18.24.2
ASTERISK_BASEFILENAME=asterisk-$ASTERISK_VERSION
ASTERISK_FILENAME=$ASTERISK_BASEFILENAME.tar.gz
ASTERISK_URL=http://downloads.asterisk.org/pub/telephony/asterisk/old-releases/$ASTERISK_FILENAME
